name: Make upstream PR
on:
  workflow_dispatch:
jobs:
  make_upstream_pr:
    name: Make upstream PR
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
          fetch_depth: 0

      - name: Add remote, branch, and push
        run: |
          git remote add upstream https://github.com/cnunciato/some-public-repo.git
          git fetch --unshallow upstream
          git checkout -b some-branch
          git push upstream some-branch
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
        
